
LambdaFunctionprojectName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: projectName/function
      Handler: DotnetFunction.Function::LambdaHandler
      Runtime: runtimeName
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE