
LambdaFunctionprojectName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: projectName/
      Handler: index.handler
      Runtime: runtimeName
      Architectures:
        - x86_64